trajectory:
  robot:
    name: "hexacopter370"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/hexacopter370_description/urdf/hexacopter370.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/hexacopter370.yaml"

  stages:
    - name: "navigation"
      duration: 1100 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "CostModelState"
          weight: 1e-5
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "control_reg"
          type: "CostModelControl"
          weight: 1e-1
          reference: [0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1]

    - name: "hover"
      duration: 0 #ms
      costs:
        - name: "control_reg"
          type: "CostModelControl"
          weight: 1e-1
          reference: [0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1]

        - name: "placement_base_link"
          type: "CostModelFramePlacement"
          weight: 2000
          link_name: "hexacopter370__base_link"
          position: [0, 0, 2.5]
          orientation: [0, 0, 0, 1] # x,y,z,w

        - name: "motion_base_link"
          type: "CostModelFrameVelocity"
          weight: 1000
          link_name: "hexacopter370__base_link"
          linear: [0, 0, 0]
          angular: [0, 0, 0]
