mpc_controller:
  robot:
    # name: "hexarotor_370_flying_arm_3"
    # urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/hexarotor_370_description/urdf/hexarotor_370_flying_arm_3.urdf"
    # follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/hexacopter370.yaml"
    name: "iris"
    urdf: "/home/pepms/robotics/libraries/example-robot-data/robots/iris_description/robots/iris_simple.urdf"
    follow: "/home/pepms/robotics/libraries/multicopter-mpc/config/multicopter/iris.yaml"

  integration_method: "IntegratedActionModelEuler"
  knots: 101
  solver: "SolverSbFDDP"
  iters: 4 ,
  # weight for the carrot node
  # dt
