mission:
  $initial_state:
    - pos: [0.0, 0.0, 0.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.0]
      vel_rot: [0.0, 0.0, 0.0]

  $waypoints:    
    - pos: [0.0, 0.0, 2.0]
      quat: [0.0, 0.0, 0.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.1]
      vel_rot: [0.0, 0.0, 0.0]
      time: 2.0

    - pos: [1.0, 0.0, 3.0]
      quat: [0.0, 0.0, 1.0, 1.0] # x, y, z, w
      vel_lin: [0.0, 0.0, 0.1]
      vel_rot: [0.0, 0.0, 0.0]
      time: 1.5